### ISSUE TITLE
"Error: Failed to run docker for dart image (exit code 1})" despite Docker being installed and otherwise working.

### ISSUE THREAD

**Issue by MichaelCharles** [katallaxie/serverless-aws-dart#2]
Here is the output of `DEBUG_SLS=* sls invoke local -f hello -vvv`

```
personal/localnews_rss_lambda/hello via ⬢ v14.2.0 took 19s
➜ SLS_DEBUG=* sls invoke local -f hello -vvv
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.16.1")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Configuration warning at 'provider.runtime': should be equal to one of the allowed values [dotnetcore2.1, dotnetcore3.1, go1.x, java11, java8, java8.al2, nodejs10.x, nodejs12.x, provided, provided.al2, python2.7, python3.6, python3.7, python3.8, ruby2.5, ruby2.7]
Serverless:
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:
Serverless: Invoke invoke:local
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Building Dart main.hello func...
Serverless: Running containerized build ...
Resolving dependencies...
Downloading build_runner 1.11.0...
Downloading aws_lambda_dart_runtime 1.0.3+2...
Downloading yaml 2.2.1...
Downloading web_socket_channel 1.2.0...
Downloading watcher 0.9.7+15...
Downloading timing 0.1.1+3...
Downloading stream_transform 1.2.0...
Downloading stack_trace 1.9.6...
Downloading shelf_web_socket 0.2.4...
Downloading shelf 0.7.9...
Downloading pubspec_parse 0.1.7...
Downloading pub_semver 1.4.4...
Downloading pool 1.4.0...
Downloading pedantic 1.9.2...
Downloading path 1.7.0...
Downloading mime 0.9.7...
Downloading meta 1.2.4...
Downloading logging 0.11.4...
Downloading js 0.6.2...
Downloading io 0.3.4...
Downloading http_multi_server 2.2.0...
Downloading graphs 0.2.0...
Downloading glob 1.2.0...
Downloading dart_style 1.3.11...
Downloading crypto 2.1.5...
Downloading collection 1.14.13...
Downloading code_builder 3.6.0...
Downloading build_runner_core 6.1.6...
Downloading build_resolvers 1.5.2...
Downloading build_daemon 2.1.6...
Downloading build_config 0.4.5...
Downloading build 1.6.1...
Downloading async 2.4.2...
Downloading args 1.6.0...
Downloading json_annotation 3.1.1...
Downloading source_span 1.7.0...
Downloading string_scanner 1.0.5...
Downloading charcode 1.1.3...
Downloading stream_channel 2.0.0...
Downloading http_parser 3.1.4...
Downloading checked_yaml 1.0.4...
Downloading node_io 1.2.0...
Downloading analyzer 0.41.2...
Downloading typed_data 1.2.0...
Downloading convert 2.1.1...
Downloading matcher 0.12.9...
Downloading built_value 7.1.0...
Downloading built_collection 4.3.2...
Downloading package_config 1.9.3...
Downloading term_glyph 1.1.0...
Downloading node_interop 1.2.1...
Downloading file 5.2.1...
Downloading cli_util 0.2.0...
Downloading _fe_analyzer_shared 14.0.0...
Downloading quiver 2.1.5...
Downloading fixnum 0.10.11...
Downloading intl 0.16.1...
Got dependencies!
Generated: /tmp/tmp.VYwtl4Makj/bootstrap
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Downloading base Docker image...

{"errorType":"exitError","errorMessage":"RequestId: 3f59fa65-eb97-1e5b-a6fa-b4e87afe4fe9 Error: fork/exec /var/task/bootstrap: permission denied"}
START RequestId: 3f59fa65-eb97-1e5b-a6fa-b4e87afe4fe9 Version: $LATEST
END RequestId: 3f59fa65-eb97-1e5b-a6fa-b4e87afe4fe9
REPORT RequestId: 3f59fa65-eb97-1e5b-a6fa-b4e87afe4fe9	Init Duration: 35.93 ms	Duration: 0.58 ms	Billed Duration: 1 ms	Memory Size: 128 MBMax Memory Used: 7 MB

  Error --------------------------------------------------

  Error: Failed to run docker for dart image (exit code 1})
      at AwsInvokeLocal.invokeLocalDocker (/Users/michael/.nvm/versions/node/v14.2.0/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:510:13)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From previous event:
      at PluginManager.invoke (/Users/michael/.nvm/versions/node/v14.2.0/lib/node_modules/serverless/lib/classes/PluginManager.js:521:22)
      at /Users/michael/.nvm/versions/node/v14.2.0/lib/node_modules/serverless/lib/classes/PluginManager.js:556:24
  From previous event:
      at PluginManager.run (/Users/michael/.nvm/versions/node/v14.2.0/lib/node_modules/serverless/lib/classes/PluginManager.js:556:8)
      at /Users/michael/.nvm/versions/node/v14.2.0/lib/node_modules/serverless/lib/Serverless.js:203:33
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Serverless.run (/Users/michael/.nvm/versions/node/v14.2.0/lib/node_modules/serverless/lib/Serverless.js:190:74)
      at /Users/michael/.nvm/versions/node/v14.2.0/lib/node_modules/serverless/scripts/serverless.js:50:26

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.2.0
     Framework Version:         2.16.1
     Plugin Version:            4.3.0
     SDK Version:               2.3.2
     Components Version:        3.4.3
```

And Docker is installed and running (I use it for a lot of other projects). Here is the output of `docker info`.

```
personal/localnews_rss_lambda/hello via ⬢ v14.2.0 took 18s
➜ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 43
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.778GiB
 Name: docker-desktop
 ID: EWAK:JJDK:HJAF:SOWQ:KGES:QRGP:P4LV:XGKD:HWAI:FS22:CUWI:ZWKB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

MacOS Big Sur 11.1
node v14.2.0
serverless: Framework Core: 2.16.1 Plugin: 4.3.0 SDK: 2.3.2 Components: 3.4.3

**Comment by mcaubrey** [comment]
The actual error seems to be this I think?

```
{"errorType":"exitError","errorMessage":"RequestId: 3f59fa65-eb97-1e5b-a6fa-b4e87afe4fe9 Error: fork/exec /var/task/bootstrap: permission denied"}
```

Something about the permissions on `/var/task/bookstrap`, which I'm pretty sure is inside of the Docker container used to run the function. I'm not sure how to go about verifying that/debugging that though.

**Comment by MichaelCharles** [comment]
I'm assuming it has to do with this

```
{"errorType":"exitError","errorMessage":"RequestId: 3f59fa65-eb97-1e5b-a6fa-b4e87afe4fe9 Error: fork/exec /var/task/bootstrap: permission denied"}
```

I tried poking around at the `serverless-dart` repo to see if I could figure anything out, but haven't found anything yet.

**Comment by katallaxie** [comment]
@mcaubrey can you try with the new version of the template? https://github.com/katallaxie/serverless-dart/releases/tag/v0.0.2-beta.8 should fix this. Just tried `DEBUG_SLS=* sls invoke local -f hello -v --data '{"a":"bar"}'`. This was an issue related to the generated zip file.

**Comment by MichaelCharles** [comment]
It works! Thanks so much for looking into this!
